### ISSUE TITLE
New line after each formatted string

### ISSUE THREAD

**Issue by G-us** [pwaller/pyfiglet#101]
I'm trying to make a calculator, but I need to format different strings with different colors but when I add all the formatted strings together they each appear on a new line. I've been looking through the code for the library but can't find any thing that can help

Any ideas?

**Comment by pwaller** [comment]
I'm afraid you've not given me enough information to help efficiently here, but it doesn't sound like a problem within pyfiglet itself. If you're still around and still have this problem then feel free to continue this thread here, though I can't promise to be much help.
