### ISSUE TITLE
About packing as exe

### ISSUE THREAD

**Issue by jiananlan** [pwaller/pyfiglet#102]
I try to use the pyinstaller to turn it as a exe file. but it doesn't work finally.

**Comment by jiananlan** [comment]
sorry， the title should be ‘packaging’

**Comment by IssacLifts** [comment]
You have to manually add the 'pyfiglet' package in the packed exe

**Comment by pwaller** [comment]
I'm going to assume @IssacLifts has addressed this, if not, please comment again and we can reopen.
