### ISSUE TITLE
Lack of spaces with some fonts

### ISSUE THREAD

**Issue by victorbnl** [pwaller/pyfiglet#103]
With the font [ANSI Regular](https://github.com/xero/figlet-fonts/blob/master/ANSI%20Regular.flf), the output text lacks spaces between the letters. Which, that goes without saying, makes the text pretty much unreadable. The issue occurs only with pyfiglet and not figlet.

![image](https://user-images.githubusercontent.com/39555268/208736305-5cf0c384-5ca6-4db1-a6c4-59c74697fe97.png)

![image](https://user-images.githubusercontent.com/39555268/208736268-0000779d-9fcc-4773-8e77-bc74af0a257e.png)

**Comment by peterbrittain** [comment]
Looks like this is another difference in unicode handling.  Pyfiglet is treating unicode spaces as smushable characters, while figlet doesn't.

**Comment by pwaller** [comment]
Fix was cherry-picked onto master as 36cb512, see #120.
