### ISSUE TITLE
How to install fonts

### ISSUE THREAD

**Issue by aeciobf** [pwaller/pyfiglet#104]
I've try to install custom fonts, but the command returns error.

pyfiglet -L ansi_shadow
Usage: pyfiglet [options] [text..]
pyfiglet: error: no such option: -L

**Comment by mkinney** [comment]
Do you have a file called "ansi_shadow" in that directory? If not, it will not work.

Did you install using pip? (ex: `pip install pyfiglet`)

**Comment by peterbrittain** [comment]
The -L option was only added in later releases.  What version are you running?

**Comment by pwaller** [comment]
I'm going to close this as assumed fixed. If anyone still has a problem, feel free to ping this thread with more information and I'll reopen, or file a new issue.
