### ISSUE TITLE
Migrate from pkg_resources to importlib

### ISSUE THREAD

**Issue by Alienrazor** [pwaller/pyfiglet#113]
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by stefanor** [comment]
@Alienrazor: `pip install setuptools`

I guess we should migrate to importlib.

**Comment by Alienrazor** [comment]
Thanks so much

**Comment by pwaller** [comment]
> I guess we should migrate to importlib.

Someone want to open an issue or pull request describing what's going on? I'm not fully in the loop.

**Comment by stefanor** [comment]
setuptools used to be installed in virtualenvs by default. It contains the `pkg_resources` module, that's depended on here. It's no longer installed in virtualenvs by default, as pip now builds packages in isolated environments (using PEP517)

The general replacement for pkg_resources is the stdlib `importlib`

**Comment by pwaller** [comment]
:+1:, thanks
