### ISSUE TITLE
DeprecationWarning about pkg_resources when running tests

### ISSUE THREAD

**Issue by lameTookan** [pwaller/pyfiglet#124]
### Description:

I am getting a deprecation warning related to pkg_resources when I run pytest with pyfiglet installed 

### Steps to Reproduce:

1. Install `pyfiglet`.
2. Run `pytest`.

### Expected Behavior:

Tests run without any warnings from `pyfiglet`.

### Actual Behavior:

I get the following `DeprecationWarning`:

```
(...)/venv/lib/python3.11/site-packages/pyfiglet/__init__.py:11:
DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
    import pkg_resources
```

### Environment:

- OS: MacOS
- Python Version: 3.11
- pyfiglet Version: 0.8.post1

**Comment by peterbrittain** [comment]
That was recently fixed by #114.  Taking the latest build from main should fix this.

**Comment by peterbrittain** [comment]
@pwaller - looks like a new release soon would be a good idea.

**Comment by pwaller** [comment]
Thanks, back from holiday now. I've pushed a v1.0.0rc1, please test and report back.

**Comment by pwaller** [comment]
v1.0.0 is now out, this is assumed fixed, please shout if not.
