### ISSUE TITLE
ModuleNotFoundError: no module named 'importlib.resources' when using pyfiglet==1.0.0 and Python 3.6.10

### ISSUE THREAD

**Issue by paul105** [pwaller/pyfiglet#127]
Hi!

I think that you accidentally dropped support for Python 3.6 while doing `Drop use of pkg_resources in favour of importlib.resources`.
There is no longer possibility to use pyfiglet on Py 3.6 with new pyfiglet. On Py3.7 and above it works fine.  
Py3.6: 
![image](https://github.com/pwaller/pyfiglet/assets/7142695/c9fd71b3-68c7-4069-bc01-bd85bf53e1f3)

Py3.7:  
![image](https://github.com/pwaller/pyfiglet/assets/7142695/c4f0fa7a-6771-4157-9e59-4d424c8dd39b)

Please check if this was intentional or not and possibly block pyfiglet>=1.0.0 for Python <=3.6

**Comment by peterbrittain** [comment]
Sadly, I don't think that's the end of it...  I have also seen an issue with the use of the `files` function in 3.8 builds (for a different project).  Looks like the current code only works for 3.9 and above - see https://docs.python.org/3/library/importlib.resources.html#importlib.resources.files.

It's possible that the legacy access version (see https://github.com/simonw/datasette-jupyterlite/issues/1) may fix this for earlier versions, but I don't know if that goes back to 3.6

**Comment by pwaller** [comment]
Can anyone help me with remediating this?

I think I need:
* to publish a 1.0.1 with a `requires-python >=3.9`.
* to yank version 1.0.0 so that installers don't pick it up.
* add 3.9 to CI so we can detect when we need to bump requires-python.

Did I miss anything?

**Comment by pwaller** [comment]
Version 1.0.1 is now on pypi and I have yanked 1.0.0 to prevent old versions of python from selecting it. I understand that the rc should not be selected unless a user specifies an rc or `--pre` to `pip`. Can you please test if your problem is fixed and report back?

**Comment by paul105** [comment]
@pwaller looks like 0.8.post1 is being installed for Py2.7 and Py3.6 now and 1.0.1 for e.g. Py3.9.
Thank you for taking care of this! I guess you can close this issue now.

**Comment by pwaller** [comment]
:+1: thanks for the report.
