### ISSUE TITLE
Add ability to set width to infinity

### ISSUE THREAD

**Issue by gregorni** [pwaller/pyfiglet#134]
There may be cases when one want the output not to wrap after a certain width. One could do that by setting the width in `pyfiglet.Figlet(width=x)` to something that signifies infinity, for instance `None` or `-1`.

**Comment by pwaller** [comment]
Seems like a reasonable feature request, patches welcomed, but I'm not likely to implement this soon.

**Comment by gregorni** [comment]
I could try to work on this. What do you think is better, `-1` or `None`?

**Comment by pwaller** [comment]
`-1` seems reasonable to me in this case, but I'm open to alternative approaches if you can think of something better.

**Comment by gregorni** [comment]
I like `-1`, it somehow seems intuitive, and I've seen other libraries do it that way to.

**Comment by gregorni** [comment]
Actually, I just found out infinity exists in Python natively: https://www.askpython.com/python/examples/infinity-in-python

One can just set that as the width when initializing the class, it also works.

**Comment by turkishmaid** [comment]
Well... actually...

```python
import pyfiglet  # 1.0.2
fig = pyfiglet.Figlet(font="ivrit", width=float("inf"))
text = fig.renderText("textGoesHere").split("\n")
```

dumps like so: 

```
  File "/Users/.../venv/lib/python3.10/site-packages/pyfiglet/__init__.py", line 593, in formatProduct
    buffer = self.justifyString(self.justify, buffer)
  File "/Users/.../venv/lib/python3.10/site-packages/pyfiglet/__init__.py", line 700, in justifyString
    ' ' * (self.width - len(buffer[row]) - 1)
TypeError: can't multiply sequence by non-int of type 'float'
```
