### ISSUE TITLE
Font submission?

### ISSUE THREAD

**Issue by CatPieLeaf** [pwaller/pyfiglet#139]
How can i submit my own made font?

**Comment by peterbrittain** [comment]
Great!  How about showing us a sample of the output and submit a pull request.  You can read how to do that in the github docs:

 https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by CatPieLeaf** [comment]
Oh Okay, thanks. I thought i had to send it to figlet.org or something.
