### ISSUE TITLE
Custom zipfile option does not work

### ISSUE THREAD

**Issue by maxpowa** [pwaller/pyfiglet#37]
Using -z as specified in https://github.com/pwaller/pyfiglet/blob/master/README#L68 does not work. Program exits with "pyfiglet: error: no such option: -z". Are there plans to re-implement this functionality?

**Comment by pwaller** [comment]
I've resolved this for now by updating the documentation which referred to the zipfile option. I don't know what happened to that code, sorry. If someone has a strong need for such a feature we could look at reimplementing it.
