### ISSUE TITLE
Chg log

### ISSUE THREAD

**Issue by Alexey-T** [pwaller/pyfiglet#39]
Imo. U may not agree. But i think Changelog file looks best as it's own separate file. so i can easily find this file in GH, and see changes

**Comment by pwaller** [comment]
This feels like a bit of a strange request. You were looking for it and couldn't find it, and then found it in the README? It seems like a non-issue to me. But you're welcome to send a pull request if you feel strongly about it.

**Comment by Alexey-T** [comment]
yep: I feel better not in Readme. PullRq: later maybe as not comfy at this PC ...
