### ISSUE TITLE
Random font and style? :-)

### ISSUE THREAD

**Issue by drozzy** [pwaller/pyfiglet#47]
How can I get a random font and style every time I print something?

In the examples you show:

    f = Figlet(font='slant')

But I want to have a fun slideshow with random fonts, can I do something like?

    f = Figlet(font=random.choice(available_styles))

**Comment by pwaller** [comment]
I don't see why that wouldn't work, what have you tried and what happened?

**Comment by drozzy** [comment]
@pwaller I don't know how to get a list "available styles"... :-(

**Comment by pwaller** [comment]
I think you want this function:

https://github.com/pwaller/pyfiglet/blob/master/pyfiglet/__init__.py#L117

Ping this thread if that doesn't solve it!

**Comment by iftekhar30** [comment]
you can use this code

import pyfiglet

fonts = [
    "3-d", "3x5", "5lineoblique", "slant",
    "5lineoblique","alphabet", "banner3-D",
    "doh", "isometric1", "letters",
    "alligator", "bubble"
]

f = pyfiglet.figlet_format("Text", font = ran)
print(f)
