### ISSUE TITLE
Fonts with block elements

### ISSUE THREAD

**Issue by kostasdizas** [pwaller/pyfiglet#49]
Hello, I noticed that there are not any fonts using block ascii characters, is there a specific reason for that?

I put together one by simply converting an existing one. [ansi-blocks.flf](http://d.pr/f/1dlD2)

Would it be worth submitting a pull request?

**Comment by pwaller** [comment]
I didn't notice this issue until now, apologies. You're welcome to send PRs to add fonts. Even better if the PR contains an example of the font.

I'm not aware of any specific reason block ascii characters aren't used.
