### ISSUE TITLE
pyfiglet, list fonts in python itself

### ISSUE THREAD

**Issue by freakyy85** [pwaller/pyfiglet#54]
IS there any possibility how I can list the available fonts and print them out using pure python3?

Thanks! :)

**Comment by pwaller** [comment]
I think this is `FigletFont.getFonts`? Questions of this form can be answered by [skimming the code](https://github.com/pwaller/pyfiglet/blob/6dabdb0e720b5a61d81ff819faf0ad86127275fc/pyfiglet/__init__.py#L124-L128) fairly easily. If there were not a method to get the list of fonts, you could determine how they are found (`pkg_resources.resource_string`) and then figure out how to list them from there if you had to.
