### ISSUE TITLE
More colours for output

### ISSUE THREAD

**Issue by 1605200517** [pwaller/pyfiglet#60]
Using the [`colored`](https://pypi.org/project/colored/) module, you can access quite many colors available in the terminal.

Is it anyhow possible to confugure `pyfiglet` to use color settings provided by this module?

**Comment by pwaller** [comment]
This was implemented in #57, which was not released until this moment. It is in v0.7.6.

I assume this covers your request - if not please comment what is missing.

```
pyfiglet -h
Usage: pyfiglet [options] [text..]

Options:
  [...SNIP...]
  -c COLOR, --color=COLOR
                        prints text with passed foreground color,
                        --color=foreground:background
                        --color=:background                  # only background
                        --color=foreground | foreground:     # only foreground
                        --color=list                         # list all colors
                        COLOR = list[COLOR] | [0-255];[0-255];[0-255] (RGB)
```

**Comment by pwaller** [comment]
If you take a look at the implementation of it (the diff in #57), you should be able to figure it out:

https://github.com/pwaller/pyfiglet/pull/57/files

(hint: see `print_figlet`).

**Comment by 1605200517** [comment]
great, thank you! the following works for me:

```
from pyfiglet import print_figlet
colors="38;157;127:" 
print_figlet("foobar", font="standard", colors=colors)
print_figlet("text", font="term", colors=colors)
```

**Comment by pwaller** [comment]
I think the newline is arising from the print statement here:

https://github.com/pwaller/pyfiglet/pull/57/files#diff-5a627ef23726b4ea93e7a1cfd1c675c6R60

Which currently you can't control. I'd accept a pull request to make it controllable, perhaps by allowing the `end=` parameter to be specified to the print function. It's not great, though. Perhaps we should drop it by default, but I don't have a good intuition for how this might affect existing users who may expect the additional newline to be present by now.
