### ISSUE TITLE
Cope with compressed fonts

### ISSUE THREAD

**Issue by pwaller** [pwaller/pyfiglet#63]
Came up in https://github.com/pwaller/pyfiglet/pull/61#issuecomment-444649871.

pyfiglet should interpret when a font is compressed, and uncompress it in memory.

**Comment by peterbrittain** [comment]
Note that this affects font validation as well as when it preloads the file... I might get a chance to look at it properly in a few days.

**Comment by pwaller** [comment]
Fixed in #64, to my knowledge.
