### ISSUE TITLE
Wheel file

### ISSUE THREAD

**Issue by SecT0uch** [pwaller/pyfiglet#66]
I'm distributing my program using pynsist.
It allows to import packages on a chosen version only if a .whl is available on pypi.
It would be much more easy to distribute.
Would it be possible to do it and publish future releases with a wheel file ?

**Comment by pwaller** [comment]
I've just published https://pypi.org/project/pyfiglet/0.8.post1/#files - does that satisfy your need?

**Comment by SecT0uch** [comment]
Awesome ! Thanks for the reactivity.
Very efficient !
