### ISSUE TITLE
Font 5x8 is corrupted, I fixed it!

### ISSUE THREAD

**Issue by jneb** [pwaller/pyfiglet#69]
The font 5x8 was corrupt, since the font file had 9 lines per character. Here  is the fixed file.
[5x8.flf.txt](https://github.com/pwaller/pyfiglet/files/3157385/5x8.flf.txt)

**Comment by pwaller** [comment]
Thanks, are you able to send a pull request?

Please also include a reproducer which demonstrates what was broken, even if it is something obvious.

**Comment by jneb** [comment]
I just learnt this week how to do that. Nice Christmas activity :-)
Jurjen

Op vr 13 dec. 2019 21:11 schreef Peter Waller <notifications@github.com>:

**Comment by peterbrittain** [comment]
Fixed in https://github.com/pwaller/pyfiglet/pull/123
