### ISSUE TITLE
Can we put art text and normal text side by side"

### ISSUE THREAD

**Issue by LeZhengThu** [pwaller/pyfiglet#72]
Hi all,
     I wonder if there's a way to put the art text and normal text side by side, just like content in the pic below? Thanks.
![image](https://user-images.githubusercontent.com/18341929/63186188-b0d0e280-c010-11e9-9f58-771a83268ff6.png)

**Comment by pwaller** [comment]
There is not a way to do this built into pyfiglet, sorry. If you want to contribute a patch to do this, feel free to discuss the design here first before trying to submit a pull request, in case someone chimes in. If so, I will reopen the issue.
