### ISSUE TITLE
Support for --color on Windows?

### ISSUE THREAD

**Issue by amitbora007** [pwaller/pyfiglet#73]
unable to use '-color','--color' parameter in both CLI and library import method.
please provide any usage example

**Comment by pwaller** [comment]
I'm unsure quite what to make of your issue.

What did you try doing so far, and where did you look to try? It works for me:

![Screenshot from 2020-01-17 21-18-46](https://user-images.githubusercontent.com/438648/72646848-fce0d400-396e-11ea-9b3a-c866ab9c6138.png)

**Comment by amitbora007** [comment]
I am getting this result with the same command. Is this module specific for some IDE or terminal? I am working on windows using anaconda prompt.
![image](https://user-images.githubusercontent.com/17309575/72679887-cbd0e280-3ad9-11ea-87a8-70e99cf8a6e1.png)

**Comment by pwaller** [comment]
Ah, I am unfamiliar with the behaviour of pyfiglet on windows, and this is untested, sorry. It looks like windows doesn't use the same representation to control color. I'm afraid I don't know how to fix this and we need to find a willing windows developer to help out.

**Comment by amitbora007** [comment]
> Ah, I am unfamiliar with the behaviour of pyfiglet on windows, and this is untested, sorry. It looks like windows doesn't use the same representation to control color. I'm afraid I don't know how to fix this and we need to find a willing windows developer to help out.

okk, thanks for the reply. I will also update if find any fix for this.

**Comment by grandemk** [comment]
I believe you could do something like that:
try:
    from colorama import init
    init(strip=not sys.stdout.isatty())
    from termcolor import cprint
except:
    def cprint(text, color):
       // use default of pyfliglet colors implementation without dependencies

And then adapt the code in pyfiglet to use that.
On windows, you would just need to pip install colorama and termcolor to get the color support.

**Comment by pwaller** [comment]
If possible it would be great to avoid pulling in another dependency.

At time of writing we have [~300 dependent packages and ~6,000 dependent repositories](https://github.com/pwaller/pyfiglet/network/dependents). Adding an extra dependency means affecting all those other packages. Going from 0 to 1 dependency is a significant step and I don't know how to make it whilst being sure not to break backwards compatibility for everyone.

**Comment by mixmastamyk** [comment]
@amitbora007 it looks like your legacy console doesn't support ANSI sequences.  If you have a recent version of Windows you can typically enable it on the console settings panel (at top left).  Windows terminal might be another option.

Another option is to use colorama, although it isn't necessary any longer to include it as a dependency due to widespread ANSI support.

**Comment by mkinney** [comment]
Ok to close? Looks resolved to me. (use a different console on windows)

**Comment by pwaller** [comment]
I'm happy to close this, please comment to request a reopen (with some details as to why) if needed.
