### ISSUE TITLE
Umlaute

### ISSUE THREAD

**Issue by u0nel** [pwaller/pyfiglet#80]
The Umlauts ä, ü and ö don't work even though, the font has them.

**Comment by pwaller** [comment]
Research and patches welcomed! Sorry I don't have time to delve in myself but I will do code review.

**Comment by unbeatable-101** [comment]
What font?

**Comment by everlanes** [comment]
Added a patch to load the German Umlaute in the __init__.py - not changing the font format.
This patch will solve the issue for all fonts that have the umlaute defined.

**Comment by pwaller** [comment]
Merged in #96.
