### ISSUE TITLE
setuptools missing from requirements.txt

### ISSUE THREAD

**Issue by leonardp** [pwaller/pyfiglet#87]
`pkg_resources` imported here: https://github.com/pwaller/pyfiglet/blob/master/pyfiglet/__init__.py#L11 is part of setuptools so it should be added to requirements.txt as otherwise pyfiglet raises:
```
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by lasantha-kumara** [comment]
can u give this to me

**Comment by pwaller** [comment]
I believe this should have been fixed in #114 which moved pyfiglet away from setuptools. I believe that in a near future release of pyfiglet (>0.8.post0, not yet out at time of writing, but soon), this should no longer be an issue.
