### ISSUE TITLE
Thank you!  ❤ your contribution to available Python packages....

### ISSUE THREAD

**Issue by PySimpleGUI** [pwaller/pyfiglet#93]
I don't see a sponsor button, so I'm going to at least say

```
M""""""""M dP                         dP       
Mmmm  mmmM 88                         88       
MMMM  MMMM 88d888b. .d8888b. 88d888b. 88  .dP  
MMMM  MMMM 88'  `88 88'  `88 88'  `88 88888"   
MMMM  MMMM 88    88 88.  .88 88    88 88  `8b. 
MMMM  MMMM dP    dP `88888P8 dP    dP dP   `YP 
MMMMMMMMMM                                     
                                               
M""MMMM""M                   dP 
M. `MM' .M                   88 
MM.    .MM .d8888b. dP    dP 88 
MMMb  dMMM 88'  `88 88    88 dP 
MMMM  MMMM 88.  .88 88.  .88    
MMMM  MMMM `88888P' `88888P' oo 
MMMMMMMMMM
```

You've made my code so much more enjoyable, fun, and provided the library that [my GUI](https://github.com/PySimpleGUI/psgfiglet) sits on top of.  Without your code, there would be no figlets in my code.

Much happier code after finding `pyfiglet`

![image](https://user-images.githubusercontent.com/46163555/147674980-a8c1a601-784c-42e9-8374-46bf9bb45e16.png)

**Comment by pwaller** [comment]
Thanks for taking the time to share your gratitude ❤️ All the best to you.

I am but a small piece of this project as a mere maintainer, so I'd like to pass my thanks on to everyone who contributed, big and small too. Sorry if I missed anyone off the list!

@cjones @stefanor @peterbrittain @grandemk @marlboromoo @Alexey-T @MinchinWeb @aerickson @asakasinsky @livibetter @pmlandwehr @timgates42 @llimllib @u0nel @BjornFJohansson @irskep @mnunezdm

**Comment by PySimpleGUI** [comment]
While we're in recognition mode, I definitely need to recognize @nycynik, who is listed in my source file with the link:
https://github.com/nycynik/ascii-font-processor
but I'll be adding to my readme too... 

![image](https://user-images.githubusercontent.com/46163555/147863527-a58fa7b1-db34-45af-8c53-983ebf690e26.png)

Proper respect for everyone involved.  

There are figlets all over the PySimpleGUI code. The  PySimpleGUI.py file has a number of them in different formats.

![image](https://user-images.githubusercontent.com/46163555/147863558-453d1331-4c4f-4b90-9383-d7f20b33db55.png)

![image](https://user-images.githubusercontent.com/46163555/147863562-3ec4ea38-a24e-4766-b7d5-06b67797ae45.png)

They fun, really helpful for marking sections.

**Comment by PySimpleGUI** [comment]
Fixed up the [readme](https://github.com/PySimpleGUI/psgfiglet).... I also had not properly credited the psgfiglet team there.  It's a never-ending education and I really want to make sure all this work you're putting in is acknowledged.  🙏

**Comment by pwaller** [comment]
Thanks again, closing to remove from the list of open issues :)

**Comment by PySimpleGUI** [comment]
By all means, close those issues!  Clear that queue

![image](https://user-images.githubusercontent.com/46163555/170524383-adda4f3c-a6ff-4c19-ac00-07326b6e6f74.png)

Thank you again for writing a great piece of code!
