### ISSUE TITLE
Problem with standalone JupyterLab on Windows

### ISSUE THREAD

**Issue by miklevin** [pwaller/pyfiglet#94]
pyfiglet doesn't import. Here's the error:

import pyfiglet
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_17912/2380198760.py in <module>
----> 1 import pyfiglet

C:\JupyterLab\resources\jlab_server\lib\site-packages\pyfiglet\__init__.py in <module>
     57 
     58 if sys.platform == 'win32':
---> 59     SHARED_DIRECTORY = os.path.join(os.environ["APPDATA"], "pyfiglet")
     60 else:
     61     SHARED_DIRECTORY = '/usr/local/share/pyfiglet/'

C:\JupyterLab\resources\jlab_server\lib\os.py in __getitem__(self, key)
    673         except KeyError:
    674             # raise KeyError with the original key value
--> 675             raise KeyError(key) from None
    676         return self.decodevalue(value)
    677 

KeyError: 'APPDATA'

And here's the contents of os.environ

environ{'HOMEDRIVE': 'C:',
        'HOMEPATH': '\\Users\\mike',
        'JUPYTER_CONFIG_DIR': 'C:\\Users\\mike\\AppData\\Roaming\\jupyterlab-desktop',
        'JUPYTER_TOKEN': 'foo(removed)', 
        'LOGONSERVER': '\\\\LUNDERVAND',
        'PATH': 'C:\\JupyterLab\\resources\\jlab_server;C:\\JupyterLab\\resources\\jlab_server\\Library\\mingw-w64\\bin;C:\\JupyterLab\\resources\\jlab_server\\Library\\usr\\bin;C:\\JupyterLab\\resources\\jlab_server\\Library\\bin;C:\\JupyterLab\\resources\\jlab_server\\Scripts;C:\\JupyterLab\\resources\\jlab_server\\bin;C:\\Python39\\Scripts\\;C:\\Python39\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\JupyterLab;C:\\Users\\mike\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\mike\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\mike\\AppData\\Roaming\\npm',
        'SYSTEMDRIVE': 'C:',
        'SYSTEMROOT': 'C:\\WINDOWS',
        'TEMP': 'C:\\Users\\mike\\AppData\\Local\\Temp',
        'USERDOMAIN': 'LUNDERVAND',
        'USERNAME': 'mike',
        'USERPROFILE': 'C:\\Users\\mike',
        'WINDIR': 'C:\\WINDOWS',
        'PYDEVD_USE_FRAME_EVAL': 'NO',
        'JPY_INTERRUPT_EVENT': '2248',
        'IPY_INTERRUPT_EVENT': '2248',
        'JPY_PARENT_PID': '1996',
        'TERM': 'xterm-color',
        'CLICOLOR': '1',
        'PAGER': 'cat',
        'GIT_PAGER': 'cat',
        'MPLBACKEND': 'module://matplotlib_inline.backend_inline'}

And here's the JupyterLab version (standalone / Electron app): Version 3.2.5-1

**Comment by diamant3** [comment]
Try this: `python -m pip install pyfiglet`. You need to use what jupyterlab-desktop's python uses.

**Comment by pwaller** [comment]
Yeah, I'm not sure what to make of this, it suggests the APPDATA environment variable is not set? I don't have a windows environment to experiment with but I thought that was a fairly important environment variable. 

I'm going to close on the assumption that this does not remain an issue. If it remains an issue please comment and we can reopen. I would need help to get to the bottom of it though.
